name: deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Restore yarn cache
      uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install npm modules
      run:
        yarn install
    - name: Build app
      run:
        yarn predeploy
    - name: Deploy hosting
      run: |
        ./node_modules/.bin/firebase deploy -P default --only hosting --token=${{ secrets.FIREBASE_TOKEN }}
    # - name: Slack Notification
    #   uses: homoluctus/slatify@master
    #   if: always()
    #   with:
    #     type: ${{ job.status }}
    #     job_name: '*Deploy Site*'
    #     mention: 'here'
    #     mention_if: 'failure'
    #     channel: '#github_website'
    #     url: ${{ secrets.SLACK_WEBHOOK }}
    #     commit: true
    #     token: ${{ secrets.GITHUB_TOKEN }}
